# Plugins
gems:
- jekyll-redirect-from
- jekyll-paginate
safe: false

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ['/scripts/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Technology Robotix Society, IIT Kharagpur"
description: "Technology Robotix Society is an official society under the Technology Students' Gymkhana IIT Kharagpur."
baseurl: "https://2016.robotix.in"
permalink: "/blog/:title/"
collections:
  events:
    output: true
    permalink: "/event/:path/"
  tutorials:
    output: true
    permalink: "/tutorial/:path/"

#Pagination
paginate: 10
paginate_path: "/blog/:num"

# Head
metaKeywords: "robotix, robotics, iit, kgp, team, events, society, technology, tutorial"
twitterAccount: "@robotixiitkgp"
google-plus-page: "https://plus.google.com/102868621563384739622"
siteVerification: "ZR618hQWwV_OwtWa033492kzvBaQYxBc1ZauYc5oO5A"
fbAdmin: "100002238663887"
socialImage: "/img/favicons/favicon-196x196.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/event/", text: "Events"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/tutorial", text: "Tutorials"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/about-us/", text: "About Us"}
 - {permalink: "/alumni/", text: "Alumni"}
bottomNavigationLinks:
 - {link: "http://contact.robotix.in", text: "Contact Us"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "21st Jan - 24th Jan, 2016"
typeoutTextValues: '"Technology Robotix Society", "Where Machines Dare!", "#GearUp", "Robotix 2016"'
typeoutFallback: "Technology Robotix Society"
heroButtons:
 - {permalink: "/schedule", text: "Event Schedule"}
 - {permalink: "/noticeboard", text: "Fest Noticeboard"}

# About Block
aboutTitle: "We believe in sharing our knowledge"
aboutBlock:
  - 
    title: "K.R.A.I.G."
    image: "hackathon.jpg"
    text: "Kickstart your journey into the world of hobby robotics."
    link: "/kraig/"
  - 
    title: "K.R.I.S.S."
    image: "workshop.jpg"
    text: "To bring together people, to discuss and exchange ideas related to more mature and nuanced areas of robotics."
    link: "/kriss/"
  - 
    title: "Winter Workshop"
    image: "rse.jpg"
    text: "See the complete documentation of the winter workshop we conduct anually for first and second year undergraduates of IIT Kharagpur."
    link: "/winter-workshop/"

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "2000", specialCharacter: "+", info: "participants"}
 - {count: "500", specialCharacter: "+", info: "teams"}
 - {count: "6", specialCharacter: "", info: "events"}
 - {count: "1", specialCharacter: "", info: "fest"}
statisticQuirk: "Robotix 2015 in numbers"

# Latest News Block
latestNewsTitle: "Latest blog articles"
latestNewsCount: 2
latestNewsButtonText: "Explore our blog"

# Facebook Feed Block
FbFeedTitle: "Are You Geared Up?"
FbHashTag: "robotixiitkgp"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://robotix.us8.list-manage.com/subscribe/post?u=175d25a13bb44ffe7478a4ccf&amp;id=8de4186fe7"
subscribeInfo: "Subscribe with us to stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/102868621563384739622/", icon: "google-plus"}
 - {link: "https://twitter.com/RobotixIITKgp", icon: "twitter"}
 - {link: "https://facebook.com/robotixiitkgp", icon: "facebook"}
 - {link: "http://www.youtube.com/robotixiitkgp", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://play.google.com/store/apps/details?id=in.robotix.robotixapp", text: "Robotix App"}
   - {link: "https://robotix.in/event/", text: "Events"}
   - {link: "https://robotix.in/tutorial/", text: "Tutorials"}
 -
  title: "Contacts"
  links:
   - {link: "http://contact.robotix.in", text: "Contact Us"}

# Blog
blogCommentsEnabled: true
discusShortName: "robotix"

# Speakers List Block
showSessions: true

#AboutUs
whoAreWe: "Technology Robotix Society is an official society under the Technology Students' Gymkhana, IIT Kharagpur, and is a focal point for activities and projects related to robotics in the campus. With its reach expanding steadily each year, it has also cemented its position as one of the nerve centres of amateur robotics in India."
whatDoWeDo: "We are involved in various initiatives in the field of robotics throughout the year. Our flagship accomplishment is our annual competition ROBOTIX, which is held during KSHITIJ at IIT Kharagpur, and is one of the biggest such events in Asia. Every year we have increasingly capable and motivated participants tackling our novel problem statements and thereby inspiring us to organize each year's fest with renewed zeal. Another important agenda of ours is to spread the culture of robotics across India and we do this by organizing and conducting workshops and demonstrations, and in Kharagpur, besides this, by other in-house events too."
